refactor

diff --git a/src/packages/zsh/.zsh/functions b/src/packages/zsh/.zsh/functions
--- a/src/packages/zsh/.zsh/functions
+++ b/src/packages/zsh/.zsh/functions
@@ -2,6 +2,15 @@
 # shellcheck source=../../../lib/utils
 source "$DOTFILES_DIR"/src/lib/utils
 
+error() {
+    echo -e "${n}${RED}[ERROR]\t${NC}$1"
+}
+
+fatal() {
+    echo -e "${n}${CYAN}[FATAL]\t${NC}$1"
+    exit 1
+}
+
 util_terminal_colors() {
     for i in {0..255}; do
         printf "\x1b[48;5;%sm%3d\e[0m " "$i" "$i"
@@ -55,4 +64,34 @@ util_untar() {
 
 util_tar() {
     tar -cvzf "$1".tar.gz "$1"
+}
+
+install() {
+    cat <<EOF >demo.txt
+cd "$HOME"
+echo "$PWD" # echo the current path
+echo "this is plain text"
+EOF
+    if target_is_macos; then
+        cd "$DOTFILES_DIR" || fatal "couldn't cd to dotfiles dir, exiting"
+        git stash -u
+        brew install "$@"
+        rm Brewfile Brewfile.lock.json
+        brew bundle dump "$DOTFILES_DIR"/Brewfile
+        brew update
+        git add Brewfile Brewfile.lock.json
+        git commit <<EOF
+dotbot: brew sync on $(fatal_portable_hostname)
+EOF
+    else
+        error "no install utility for this system"
+    fi
+}
+
+fatal_portable_hostname() {
+    if target_is_macos; then
+        scutil --get LocalHostName
+    else
+        fatal "no portal hostname for this system, bailing"
+    fi
 }
